
/**
 * THIS IS AUTOGENERATED FILE! DO NOT MODIFY THIS FILE. THIS IS AUTOGENERATED FILE!
 * THIS IS AUTOGENERATED FILE! DO NOT MODIFY THIS FILE. THIS IS AUTOGENERATED FILE!
 * THIS IS AUTOGENERATED FILE! DO NOT MODIFY THIS FILE. THIS IS AUTOGENERATED FILE!
 */

window.config = {
    'availableSuits': ["fido2-conformance-module","u2f-v1.1-conformance-module","uaf-v1.1-conformance-module","uaf-v1.1-interop-module"]
}

window.packageVersion = "1.5.2"

if(!window.forceReloadPage) {
    window.forceReloadPage = () => {
        location.reload();
    }
}

/**
 * THIS IS AUTOGENERATED FILE! DO NOT MODIFY THIS FILE. THIS IS AUTOGENERATED FILE!
 * THIS IS AUTOGENERATED FILE! DO NOT MODIFY THIS FILE. THIS IS AUTOGENERATED FILE!
 * THIS IS AUTOGENERATED FILE! DO NOT MODIFY THIS FILE. THIS IS AUTOGENERATED FILE!
 */
